#!/bin/bash
# script for java net.tinyos.tools.Send

IFS=$'\n'$' ' # make newlines and space the separators

convert_to_hexidecimal() {
   local tempvalue=$1
   if(($tempvalue < 16));  then
      value="$(echo "obase=16; $1"| bc)"
      value=$"0"$value
   else
      value="$(echo "obase=16; $1"| bc)"
   fi
}

function main() {
datalen=20
type="00"
counter=0
for j in $(cat ./PGMExample.pgm) #run through the whole file
do
   if(($counter==0)); then
      magicnr=$j
   elif(($counter==1)); then
      rows=$j
   elif(($counter==2)); then
      col=$j
      totalelement=$((rows*col))
   elif(($counter==3)); then
      highval=$j
   else
      #convert j to hexidecimal
      convert_to_hexidecimal $j
      j=$value
      data=$data$" "$j
      #(counter-3) because the first 3 values are ignored
      if(($((counter-3))%datalen==0)); then
         dtemp=$datalen
         msglen=$((datalen+2))

         #convert msglen to hexidecimal
         convert_to_hexidecimal $msglen
         msglen=$value

         #convert datalen to hexidecimal
         convert_to_hexidecimal $datalen
         datalen=$value

         echo $"counter: "$counter
         echo $"kb used: "$(($counter / 1024)) | sed 's/..$/.&/'
         echo $"data: "${data}
         sendcmd=$"java net.tinyos.tools.Send"$" 00 FF FF 00 00 "$msglen$" 22 06"$" "$type$" "$datalen$""$data
         echo "${sendcmd}"
         ${sendcmd}
         data=""
         datalen=$dtemp
         
         #(counter-3) because the first 3 values are ignored
         #last package to send
         elif((((counter-3))==totalelement)); then
            restval=$((datalen-$((totalelement%datalen))))
            ct=1
            until [ $ct -gt "$restval" ]
            do
               data=$data$" 00"
               ((ct++))
            done
            type="01"
            datalen=$((totalelement%datalen))
            convert_to_hexidecimal $datalen
            datalen=$value
            sendcmd=$"java net.tinyos.tools.Send"$" 00 FF FF 00 00 "$msglen$" 22 06"$" "$type$" "$datalen$""$data
            echo "${sendcmd}"
            ${sendcmd}
            data=""
         fi
   fi
   counter=$((counter+1))

done
echo "number of elements"
echo "${counter}"
}
#the following line I dont know why it doesnt work without
#sendcmd=$"java net.tinyos.tools.Send 00 FF FF 00 00 16 22 06 00 14 11 23 45 11 23 45 51 12 34 55 11 23 45 51 12 34 55 11 23 45"
#echo "${sendcmd}"
#${sendcmd}

main
