#ifndef PCFILE_SENDER_H
#define PCFILE_SENDER_H


typedef enum {
  PC_CONN_ERROR_UNKNOWN,
  PC_CONN_UNEXPECTED_ERROR,
  PC_CONN_NOT_CONNECTED,
  PC_CONN_ERR_DISCONNECTED
} PCFileSenderError;


#endif /* PCFILE_SENDER_H */
