#ifndef ONLINE_COMPRESSION_ALGORITHM_H
#define ONLINE_COMPRESSION_ALGORITHM_H

typedef enum {
  OCA_ERR_INVALID_FILE = 40,
} CompressionError;

enum {
  COMPRESSION_TYPE_NONE = 0
};

#endif /* ONLINE_COMPRESSION_ALGORITHM_H */
