#ifndef RADIO_SENDER2_H
#define RADIO_SENDER2_H

typedef enum {
  RS_ERR_INIT_FAILED = 2,
  RS_ERR_PROGRAMMER,
  RS_ERR_SEND_FAILED,
  RS_ERR_INVALID_STATE,
} RadioSenderError;

#endif /* RADIO_SENDER2_H */
